#!/bin/bash -l
#SBATCH -p debug # change this option for non-debug runs
#SBATCH -t 00:10:00
#SBATCH -N 12
#SBATCH -A mp309
#SBATCH -o mpi24.%j.stdout
#SBATCH -e mpi24.%j.error

srun -n 12 ./mpi -n 5000 -o mpi.txt
